const { format } = require("morgan")

let dbName = "on-memory-neurotechnologies"
let collectionName = "readers"

// Currently, the database submits a single unique object
// whenever a user presses the 'down' button when scrolling.
// These objects simply only an _id generated by mongoDB, and 
// no updates are being made based on an individual user's submissions.
// Result: Going through the article once and submitting feedback submits 
// over a dozen objects to the database without any way to determine who it came from,
// nor is there currently a way to return meaningful user data to data back to project


const submitAllFeedback = async (req, res) => {
  
  try {
    await req.app.get('mongo_client').db(dbName).collection(collectionName).insertOne(req.body)
    return res.send(`Submission has been received.`);
  } catch (error) {
    console.log('error');
    console.log(error);
  }
};

module.exports = {
  submitAllFeedback: submitAllFeedback
}; 
