// *Comments about current issues with POST requests to DB
// Currently, the database submits a single unique object
// whenever a user presses the 'down' button when scrolling.
// These objects simply only an _id generated by mongoDB, and 
// no updates are being made based on an individual user's submissions.
// Result: Going through the article once and submitting feedback submits 
// over a dozen objects to the database without any way to determine who it came from,
// nor is there currently a way to return meaningful user data to data back to project

let dbName = "on-memory-neurotechnologies"
let collectionName = "readers"

MongoClient.connect(url, function(err, db) {
    if (err) throw err;
    var test = {userID: "abc"};
    var newTest = { userID: "def" };
    db.collection("readers").updateOne(test, newTest, function(err, res) {
      if (err) throw err;
      console.log("Document updated");
    });
  }); 

*/